config/routes.rb
TianTian::Application.routes.draw do
  config_vars

  resources :papers

  root :to => "papers#index"

end

app/models/paper.rb
# Template for a paper with practice squares.
class Paper < ActiveRecord::Base
  include Prawn::Measurements
  
  # User-friendly template name.
  validates :name, :length => 1..64, :presence => true, :uniqueness => true
  
  # Paper width, in PDF units.
  validates :layout_width, :numericality => { :greater_than => 0 },
                           :presence => true
  # Paper height, in PDF units.
  validates :layout_height, :numericality => { :greater_than => 0 },
                           :presence => true
  # User-friendly name for the paper dimensions (e.g. A4).
  validates :layout_name, :length => 1..16, :presence => true
  
  # Space left at the top of the paper, in cm.
  validates :margin_top, :numericality => { :greater_than_or_equal_to => 0 },
                         :presence => true
  # Space left at the bottom of the paper, in cm.
  validates :margin_bottom, :numericality => { :greater_than_or_equal_to => 0 },
                            :presence => true
  # Space left at the left of the paper, in cm.
  validates :margin_left, :numericality => { :greater_than_or_equal_to => 0 },
                          :presence => true
  # Space left at the right of the paper, in cm.
  validates :margin_right, :numericality => { :greater_than_or_equal_to => 0 },
                           :presence => true

  # The size of a square character cell, in cm.
  validates :cell_size, :numericality => { :greater_than_or_equal_to => 0 },
                         :presence => true
  # The space between two groups of rows cells, in cm.
  validates :group_spacing, :numericality => { :greater_than_or_equal_to => 0 },
                            :presence => true
  # The number of rows in a group.
  validates :group_rows, :presence => true, :numericality =>
      { :greater_than => 0, :only_integer => true }

  # Number of horizontal guide lines in a cell.
  validates :horizontal_guides, :presence => true, :numericality =>
      { :greater_than_or_equal_to => 0, :only_integer => true }
  # Number of vertical guide lines in a cell.
  validates :vertical_guides, :presence => true, :numericality =>
      { :greater_than_or_equal_to => 0, :only_integer => true }
  # Whether cells have diagonal guide lines making up a cross-hatch.
  validates :diagonal_guides, :inclusion => { :in => [true, false] }
  
  # Width of the cell border lines, in mm.
  validates :cell_stroke_size, :numericality => { :greater_than => 0 },
                               :presence => true
  # Width of the guide lines inside cells, in mm.
  validates :guide_stroke_size, :numericality => { :greater_than => 0 },
                                :presence => true

  # Color of the cell border lines, formated as rrggbb hex digits.
  validates :cell_stroke_color, :format => /^[0-9a-f]{6}$/,
                                :presence => true

  # Color of the guide lines inside cells, formated as rrggbb hex digits.
  validates :guide_stroke_color, :format => /^[0-9a-f]{6}$/,
                                 :presence => true


  # :nodoc: auto-fills width and height
  def layout_name=(new_layout)
    super
    layout = Prawn::Document::PageGeometry::SIZES[new_layout]
    self.layout_width, self.layout_height = *layout
  end
  
  # PDF bits.
  def to_pdf
    pdf = Prawn::Document.new :page_size => [layout_width, layout_height],
                              :margin => 0
    pdf_grid pdf
    pdf.render
  end
  
  # Draws the grid on a PDF document.
  def pdf_grid(pdf)
    groups = self.grid_row_groups
  
    0.upto(groups - 1) do |group|
      0.upto(group_rows - 1) do |row|
        pdf_grid_row pdf, group_rows * (groups - group) - row,
            margin_bottom_pdf +
            (cell_size_pdf * group_rows + group_spacing_pdf) * group +
            cell_size_pdf * row
      end
    end
  end
  
  # Draws a grid row on a PDF document.
  def pdf_grid_row(pdf, row_number, y_bottom)
    columns = self.grid_columns
    
    left = margin_left_pdf
    right = left + cell_size_pdf * columns
    bottom = y_bottom
    top = bottom + cell_size_pdf
    
    # Guide lines.
    old_stroke_color = pdf.stroke_color
    pdf.stroke_color = guide_stroke_color
    pdf.line_width guide_stroke_size_pdf
    pdf.stroke do
      spacing = cell_size_pdf / (1 + horizontal_guides)
      1.upto(horizontal_guides) do |i|
        pdf.line left, bottom + i * spacing, right, bottom + i * spacing
      end
      
      0.upto(columns - 1) do |j|
        cell_left = left + cell_size_pdf * j
        1.upto(vertical_guides) do |i|
          pdf.line cell_left + i * spacing, top, cell_left + i * spacing, bottom
        end
        
        if diagonal_guides
          pdf.line cell_left, top, cell_left + cell_size_pdf, bottom
          pdf.line cell_left + cell_size_pdf, top, cell_left, bottom
        end
      end
    end

    # Cell borders.
    pdf.stroke_color = cell_stroke_color
    pdf.line_width cell_stroke_size_pdf
    pdf.stroke do
      pdf.rectangle [left, top], columns * cell_size_pdf, cell_size_pdf
      1.upto(columns - 1) do |i|
        pdf.line left + cell_size_pdf * i, top, left + cell_size_pdf * i, bottom
      end
    end
    pdf.stroke_color = old_stroke_color
  end
  
  # Number of grid row groups that will fit on a page.
  def grid_row_groups
    height = layout_height - margin_bottom_pdf - margin_top_pdf
    group_height = cell_size_pdf * group_rows
    
    1 + ((height - group_height) /
         (group_height + group_spacing_pdf).to_f).floor
  end
  
  # Number of grid rows that will fit on a page.
  def grid_rows
    grid_row_groups * group_rows
  end
    
  # Number of character squares in each row that will fit on a page.
  def grid_columns
    width = layout_width - margin_left_pdf - margin_right_pdf
    (width / cell_size_pdf.to_f).floor
  end

  # Handy methods for converting from cm to PDF-native units.
  [
    :margin_top, :margin_bottom, :margin_left, :margin_right,
    :cell_size, :group_spacing
  ].each do |size|
    define_method :"#{size}_pdf" do
      cm2pt self.send(size)
    end
  end
  [:cell_stroke_size, :guide_stroke_size].each do |size|
    define_method :"#{size}_pdf" do
      mm2pt self.send(size)
    end
  end
  
  def load_defaults
    self.layout_name = 'LETTER'
    self.margin_top = 2
    self.margin_bottom = 1
    self.margin_left = 2.5
    self.margin_right = 2
    
    self.cell_size = 1.2
    self.group_spacing = 1.32
    self.group_rows = 1
    
    self.horizontal_guides = 0
    self.vertical_guides = 0
    self.diagonal_guides = false
    
    self.cell_stroke_size = 0.5
    self.guide_stroke_size = 0.1
    self.cell_stroke_color = '000000'
    self.guide_stroke_color = '666666'
  end
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  config_vars_auth :except => [:index, :show]
  
  # GET /papers
  # GET /papers.json
  def index
    @papers = Paper.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @papers }
    end
  end

  # GET /papers/1
  # GET /papers/1.pdf
  # GET /papers/1.json
  def show
    @paper = Paper.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.pdf do
        send_data @paper.to_pdf, :format => 'application/pdf',
                                 :filename => "#{@paper.name}.pdf"
      end
      format.json { render :json => @paper }
    end
  end

  # GET /papers/new
  # GET /papers/new.json
  def new
    @paper = Paper.new
    @paper.load_defaults

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @paper }
    end
  end

  # GET /papers/1/edit
  def edit
    @paper = Paper.find(params[:id])
  end

  # POST /papers
  # POST /papers.json
  def create
    @paper = Paper.new(params[:paper])

    respond_to do |format|
      if @paper.save
        format.html { redirect_to(papers_url, :notice => 'Template created.') }
        format.json { render :json => @paper, :status => :created, :location => @paper }
      else
        format.html { render :action => :new }
        format.json { render :json => @paper.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /papers/1
  # PUT /papers/1.json
  def update
    @paper = Paper.find(params[:id])

    respond_to do |format|
      if @paper.update_attributes(params[:paper])
        format.html { redirect_to(papers_url, :notice => 'Template updated.') }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @paper.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /papers/1
  # DELETE /papers/1.json
  def destroy
    @paper = Paper.find(params[:id])
    @paper.destroy

    respond_to do |format|
      format.html { redirect_to(papers_url) }
      format.json { head :ok }
    end
  end
end

app/helpers/papers_helper.rb
module PapersHelper
  include Prawn::Measurements
  
  def layout_name_options
    Prawn::Document::PageGeometry::SIZES.map { |key, value|
      ["#{key.downcase.capitalize} (#{pt2mm(value.first).to_i}mm x #{pt2mm(value.last).to_i}mm)", key]
    }.sort
  end
end

app/views/papers/_form.html.erb
<%= form_for(@paper) do |f| %>
  <% if @paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paper.errors.count, "error") %> prohibited this paper from being saved:</h2>

      <ul>
      <% @paper.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <section class="fields">
    <p class="field">
      <%= f.label :name, 'Template name' %>
      <span class="value">
        <%= f.text_field :name, :required => true %>
      </span>
    </p>

    <p class="field">
      <%= f.label :layout_name, 'Paper layout' %>
      <span class="value">
        <%= f.select :layout_name, layout_name_options %>
      </span>
    </p>

    <p class="field">
      <%= f.label :margin_top, 'Top margin' %>
      <span class="value">
        <%= f.number_field :margin_top, :min => 0, :step => 0.01,
                                        :required => true %>
      </span>
      <span class="comment">cm</span>
    </p>
    <p class="field">
      <%= f.label :margin_bottom, 'Bottom margin' %>
      <span class="value">
        <%= f.number_field :margin_bottom, :min => 0, :step => 0.01,
                                           :required => true %>
      </span>
      <span class="comment">cm</span>
    </p>
    <p class="field">
      <%= f.label :margin_left, 'Left margin' %>
      <span class="value">
        <%= f.number_field :margin_left, :min => 0, :step => 0.01,
                                         :required => true %>
      </span>
      <span class="comment">cm</span>
    </p>
    <p class="field">
      <%= f.label :margin_right, 'Right margin' %>
      <span class="value">
        <%= f.number_field :margin_right, :min => 0, :step => 0.01,
                                          :required => true %>
      </span>
      <span class="comment">cm</span>
    </p>

    <p class="field">
      <%= f.label :cell_size, 'Character square side' %>
      <span class="value">
        <%= f.number_field :cell_size, :min => 0, :step => 0.01,
                                       :required => true %>
      </span>
      <span class="comment">cm</span>
    </p>
    <p class="field">
      <%= f.label :group_spacing, 'Space between row groups' %>
      <span class="value">
        <%= f.number_field :group_spacing, :min => 0, :step => 0.01,
                                           :required => true %>
      </span>
      <span class="comment">cm</span>
    </p>
    <p class="field">
      <%= f.label :group_rows, 'Character rows in a group' %>
      <span class="value">
        <%= f.number_field :group_rows, :min => 0, :step => 1,
                                        :required => true %>
      </span>
    </p>

    <p class="field">
      <%= f.label :horizontal_guides,
                  'Horizontal guide lines inside a square' %>
      <span class="value">
        <%= f.number_field :horizontal_guides, :min => 0, :step => 1,
                                               :required => true %>
      </span>
    </p>
    <p class="field">
      <%= f.label :vertical_guides,
                  'Vertical guide lines inside a square' %>
      <span class="value">
        <%= f.number_field :vertical_guides, :min => 0, :step => 1,
                                             :required => true %>
      </span>
    </p>
    <p class="field">
      <%= f.label :diagonal_guides,
                  'Diagonal guide lines inside a square' %>
      <span class="value">
        <%= f.check_box :diagonal_guides %>
        diagonal guides make up a cross in each square
      </span>
    </p>

    <p class="field">
      <%= f.label :cell_stroke_size, 'Width of character square borders' %>
      <span class="value">
        <%= f.number_field :cell_stroke_size, :min => 0, :step => 0.01,
                                              :required => true %>
      </span>
      <span class="comment">mm</span>
    </p>
    <p class="field">
      <%= f.label :cell_stroke_color, 'Color of character square borders' %>
      <span class="value">
        <%= f.text_field :cell_stroke_color, :required => true %>
      </span>
      <span class="comment">rrggbb</span>
    </p>
    <p class="field">
      <%= f.label :guide_stroke_size, 'Width of guide lines inside squares' %>
      <span class="value">
        <%= f.number_field :guide_stroke_size, :min => 0, :step => 0.01,
                                               :required => true %>
      </span>
      <span class="comment">mm</span>
    </p>
    <p class="field">
      <%= f.label :guide_stroke_color, 'Color of guide lines inside squares' %>
      <span class="value">
        <%= f.text_field :guide_stroke_color, :required => true %>
      </span>
      <span class="comment">rrggbb</span>
    </p>
  </section>

  <p class="actions">
    <%= f.submit 'Save Template' %>
  </p>
<% end %>

app/views/papers/edit.html.erb
<h2>Editing Sheet Template</h2>

<%= render 'form' %>

app/views/papers/index.html.erb
<h2>Sheet Templates</h2>

<table>
  <tr>
    <th>Name</th>
    <th>Paper</th>
    <th>Characters</th>
    <th>Square size</th>
    <th>Guide lines</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @papers.each do |paper| %>
  <tr>
    <td><%= paper.name %></td>
    <td><%= paper.layout_name %></td>
    <td><%= paper.grid_columns %> x <%= paper.grid_rows %></td>
    <td><%= paper.cell_size %> cm</td>
    <td>
      <%= paper.horizontal_guides %> x <%= paper.vertical_guides %>
      <% if paper.diagonal_guides %>
        + diags
      <% end %>
    </td>
    <td><%= link_to 'Generate PDF', paper_path(paper, :format => :pdf) %></td>
    <td><%= link_to 'Edit', edit_paper_path(paper) %></td>
    <td><%= link_to 'Delete', paper, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/papers/new.html.erb
<h2>New Layout</h2>

<%= render 'form' %>

app/views/papers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Layout name:</b>
  <%= @paper.layout_name %>
</p>

<p>
  <b>Layout width:</b>
  <%= @paper.layout_width %>
</p>

<p>
  <b>Layout height:</b>
  <%= @paper.layout_height %>
</p>


<%= link_to 'Edit', edit_paper_path(@paper) %> |
<%= link_to 'Back', papers_path %>