config/routes.rb
TianTian::Application.routes.draw do
  config_vars

  resources :papers

  root :to => "papers#index"

end

app/views/layouts/_footer.html.erb
<nav>
	<ul>
		<li>
      <a href="http://www.cantonese.sheik.co.uk/essays/chinesewriting.htm">
        How to write Chinese characters
      </a>
      <a href="http://en.wikipedia.org/wiki/Chinese_character">
        Chinese characters article in Wikipedia
      </a>
			<a href="https://github.com/pwnall/tian_tian">
        TianTian source code
      </a>
		</li>
	</ul>

  <p class="design">
    Designed by <a href="http://www.costan.us">Victor Costan</a>
  </p>
</nav>

app/views/layouts/_header.html.erb
<hgroup>
  <h1>
    <span class="app-name">
      TianTian
    </span>
  </h1>

  <%= render 'layouts/menu' %>
</hgroup>

app/views/layouts/_menu.html.erb
<nav>
  <ol>
    <li>
      <%= link_to 'Add Sheet Template', new_paper_path %>
    </li>
  </ol>
</nav>

app/views/layouts/_status_bar.html.erb
<% if flash[:alert] %>
<p class="status-bar error" data-pwnfx-hide-positive="status-bar">
  <%= flash[:alert] %>

  <span class="actions">
  <%= link_to 'Hide', '#', 'data-pwnfx-hide' => 'status-bar' %>
  </span>
</p>
<% elsif flash[:errors] && flash[:errors].any? %>
<div class="status-bar error" data-pwnfx-hide-positive="status-bar">
  <%= pluralize(flash[:errors].count, "error") %> occurred:
  <span class="actions">
  <%= link_to 'Hide', '#', 'data-pwnfx-hide' => 'status-bar' %>
  </span>

  <ul>
  <% flash[:errors].full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% elsif flash[:notice] %>
<p class="status-bar notice" data-pwnfx-hide-positive="status-bar">
  <%= flash[:notice] %>

  <span class="actions">
  <%= link_to 'Hide', '#', 'data-pwnfx-hide' => 'status-bar' %>
  </span>
</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>TianTian</title>
<%= csrf_meta_tag %>
<%= favicon_link_tag %>
<%= stylesheet_link_tag 'application' %>
<%= javascript_include_tag 'application' %>
</head>
<body>
<header>
<%= render 'layouts/header' %>
</header>

<div id="real-body">
<%= render 'layouts/status_bar' %>
<div id="content-wrapper">
<article id="main">
<%= yield %>
</article>
</div>
</div>

<footer>
<%= render 'layouts/footer' %>
</footer>
</body>
</html>

app/views/layouts/config_vars.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= config_vars_app_name %> Vars</title>
    <%= javascript_include_tag :defaults %>
  </head>
  <body>
    <h1><%= config_vars_app_name %> Configuration Vars</h1>
<%= yield %>
  </body>
</html>